# Generated by Django 5.2.5 on 2025-09-16 17:43

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hub_users', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CustomUserAdditionalInfos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('birth_date', models.DateField()),
                ('telephone_number', models.CharField(max_length=13)),
                ('registration', models.CharField(max_length=30)),
                ('cpf', models.CharField(max_length=11)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.DeleteModel(
            name='StudentAdditionalInfos',
        ),
    ]
