# Generated by Django 5.2.5 on 2025-09-17 21:09

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hub_users', '0002_customuseradditionalinfos_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='AdditionalInfos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('birth_date', models.DateField()),
                ('telephone_number', models.CharField(max_length=13)),
                ('registration', models.CharField(blank=True, max_length=11, null=True)),
                ('cpf', models.CharField(max_length=11)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='additional_infos', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.DeleteModel(
            name='CustomUserAdditionalInfos',
        ),
    ]
