# Generated by Django 5.2.5 on 2025-09-19 14:22

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hub_users', '0003_additionalinfos_delete_customuseradditionalinfos'),
    ]

    operations = [
        migrations.AlterField(
            model_name='additionalinfos',
            name='id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False),
        ),
    ]
