# Generated by Django 5.2.5 on 2025-09-20 20:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hub_users', '0004_alter_additionalinfos_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='additionalinfos',
            name='birth_date',
            field=models.DateField(verbose_name='Data de nascimento'),
        ),
        migrations.AlterField(
            model_name='additionalinfos',
            name='cpf',
            field=models.CharField(max_length=11, unique=True, verbose_name='CPF'),
        ),
        migrations.AlterField(
            model_name='additionalinfos',
            name='registration',
            field=models.CharField(blank=True, max_length=11, null=True, verbose_name='Matrícula'),
        ),
        migrations.AlterField(
            model_name='additionalinfos',
            name='telephone_number',
            field=models.CharField(max_length=13, verbose_name='Telefone'),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='access_profile',
            field=models.CharField(choices=[('aluno', 'Aluno'), ('servidor', 'Servidor'), ('convidado', 'Convidado')], max_length=12, verbose_name='Perfil de acesso'),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='date_joined',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Data de entrada'),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='email',
            field=models.EmailField(max_length=254, unique=True, verbose_name='Email'),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='first_login',
            field=models.BooleanField(default=True, verbose_name='Primeiro login'),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='is_abstract',
            field=models.BooleanField(default=False, verbose_name='Tipo de conta'),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='is_active',
            field=models.BooleanField(default=False, verbose_name='Status'),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='username',
            field=models.CharField(max_length=100, verbose_name='Nome'),
        ),
        migrations.AlterField(
            model_name='password',
            name='password',
            field=models.CharField(max_length=128, verbose_name='Senha'),
        ),
    ]
