# Generated by Django 5.2.2 on 2025-06-08 18:53

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='App',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=50, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Entity',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=30, unique=True)),
                ('app', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='systems.app')),
            ],
        ),
        migrations.CreateModel(
            name='System',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=50, unique=True)),
                ('system_url', models.URLField(max_length=255)),
                ('is_active', models.BooleanField()),
                ('current_state', models.CharField(choices=[('Em desenvolvimento', 'Dev'), ('Implantado', 'Deployed')], max_length=20)),
                ('secret_key', models.CharField(max_length=200)),
                ('dev_team', models.ManyToManyField(to=settings.AUTH_USER_MODEL)),
                ('groups', models.ManyToManyField(to='auth.group')),
            ],
        ),
        migrations.AddField(
            model_name='app',
            name='system',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='systems.system'),
        ),
    ]
