# Generated by Django 5.2.2 on 2025-06-17 20:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('systems', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='entity',
            name='app',
        ),
        migrations.DeleteModel(
            name='App',
        ),
        migrations.DeleteModel(
            name='Entity',
        ),
    ]
