# Generated by Django 5.2 on 2025-05-22 15:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('google_auth', '0002_remove_customuser_first_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='is_staff',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='customuser',
            name='is_superuser',
            field=models.BooleanField(default=False),
        ),
    ]
