# Generated by Django 5.2 on 2025-05-22 16:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('google_auth', '0004_alter_customuser_options_customuser_user_permissions_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Permissions',
            new_name='Permission',
        ),
    ]
