# Generated by Django 5.2 on 2025-05-28 19:38

import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='App',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=50)),
                ('app_url', models.URLField(max_length=255)),
                ('is_active', models.BooleanField()),
                ('current_state', models.CharField(choices=[('Development', 'Dev'), ('Deployed', 'Deployed')], max_length=20)),
                ('dev_team', models.ManyToManyField(to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
