# Generated by Django 5.2.5 on 2025-09-04 20:10

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Calendar',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=20)),
                ('start', models.DateField()),
                ('end', models.DateField()),
                ('status', models.CharField(choices=[('Ativo', 'Ativo'), ('Suspenso', 'Suspenso'), ('Cancelado', 'Cancelado')], max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=30)),
                ('start', models.DateField()),
                ('end', models.DateField()),
                ('type', models.CharField(choices=[('Semana Pedagógica', 'Semana Pedagogica'), ('Feriados e dias não letivos', 'Feriados N Letivo'), ('Prazo final para registro de notas e entrega de documentos', 'Prazo Fim Notas Doc'), ('Dias letivos', 'Dias Letivos'), ('Recesso Escolar/Férias', 'Recesso Esc Ferias'), ('Exames', 'Exames'), ('Conselhos de classe', 'Conselhos Classe'), ('Vestibular', 'Vestibular'), ('Fim de etapa', 'Fim Etapa')], max_length=60)),
                ('category', models.CharField(choices=[('Integrado', 'Emi'), ('ProEJA', 'Proeja'), ('Geral', 'Geral')], max_length=10)),
                ('description', models.TextField(max_length=300)),
                ('calendar', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hub_calendars.calendar')),
            ],
        ),
    ]
