# Generated by Django 5.2.5 on 2025-09-20 20:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hub_calendars', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='calendar',
            name='end',
            field=models.DateField(verbose_name='Fim'),
        ),
        migrations.AlterField(
            model_name='calendar',
            name='start',
            field=models.DateField(verbose_name='Início'),
        ),
        migrations.AlterField(
            model_name='calendar',
            name='status',
            field=models.CharField(choices=[('Ativo', 'Ativo'), ('Suspenso', 'Suspenso'), ('Cancelado', 'Cancelado')], max_length=10, verbose_name='Status'),
        ),
        migrations.AlterField(
            model_name='calendar',
            name='title',
            field=models.CharField(max_length=20, verbose_name='Título'),
        ),
        migrations.AlterField(
            model_name='event',
            name='calendar',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hub_calendars.calendar', verbose_name='Calendário'),
        ),
        migrations.AlterField(
            model_name='event',
            name='category',
            field=models.CharField(choices=[('Integrado', 'Emi'), ('ProEJA', 'Proeja'), ('Geral', 'Geral')], max_length=10, verbose_name='Categoria'),
        ),
        migrations.AlterField(
            model_name='event',
            name='description',
            field=models.TextField(max_length=300, verbose_name='Descrição'),
        ),
        migrations.AlterField(
            model_name='event',
            name='end',
            field=models.DateField(verbose_name='Fim'),
        ),
        migrations.AlterField(
            model_name='event',
            name='start',
            field=models.DateField(verbose_name='Início'),
        ),
        migrations.AlterField(
            model_name='event',
            name='title',
            field=models.CharField(max_length=30, verbose_name='Título'),
        ),
        migrations.AlterField(
            model_name='event',
            name='type',
            field=models.CharField(choices=[('Semana Pedagógica', 'Semana Pedagogica'), ('Feriados e dias não letivos', 'Feriados N Letivo'), ('Prazo final para registro de notas e entrega de documentos', 'Prazo Fim Notas Doc'), ('Dias letivos', 'Dias Letivos'), ('Recesso Escolar/Férias', 'Recesso Esc Ferias'), ('Exames', 'Exames'), ('Conselhos de classe', 'Conselhos Classe'), ('Vestibular', 'Vestibular'), ('Fim de etapa', 'Fim Etapa')], max_length=60, verbose_name='Tipo'),
        ),
    ]
