# Generated by Django 5.2.5 on 2025-09-04 20:10

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100, unique=True)),
                ('workload', models.IntegerField()),
                ('category', models.CharField(choices=[('Técnico Subsequente ao Ensino Médio', 'Tec Sub Em'), ('Técnico Integrado ao Ensino Médio', 'Tec Emi'), ('Educação de Jovens e Adultos (ProEJA)', 'Tec Proeja'), ('Especialização', 'Espec'), ('Superior', 'Sup')], max_length=37)),
            ],
        ),
        migrations.CreateModel(
            name='CourseClass',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('number', models.CharField(max_length=3, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Curriculum',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('subject_teach_workload', models.IntegerField()),
                ('subject_ext_workload', models.IntegerField()),
                ('subject_remote_workload', models.IntegerField()),
                ('period', models.IntegerField()),
                ('weekly_periods', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='PPC',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=100, unique=True)),
                ('created_at', models.DateField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Subject',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('code', models.CharField(max_length=15, unique=True)),
                ('objective', models.TextField()),
                ('menu', models.TextField()),
                ('created_at', models.DateField(auto_now_add=True)),
            ],
        ),
    ]
