# Generated by Django 5.2.4 on 2025-07-19 21:45

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Subject',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100, unique=True)),
                ('objective', models.TextField()),
                ('menu', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100, unique=True)),
                ('workload', models.IntegerField(max_length=5)),
                ('category', models.CharField(choices=[('Técnico Subsequente ao Ensino Médio', 'Tec Sub Em'), ('Técnico Integrado ao Ensino Médio', 'Tec Emi'), ('Educação de Jovens e Adultos', 'Tec Proeja'), ('Especialização', 'Espec'), ('Superior', 'Sup')], max_length=35)),
                ('coord', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Class',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('number', models.CharField(max_length=3, unique=True)),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hub_academic.course')),
            ],
        ),
        migrations.CreateModel(
            name='PPC',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=100, unique=True)),
                ('subject_teach_workload', models.IntegerField()),
                ('subject_ext_workload', models.IntegerField()),
                ('subject_remote_workload', models.IntegerField()),
                ('weekly_periods', models.IntegerField()),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hub_academic.course')),
                ('pre_requisits', models.ManyToManyField(to='hub_academic.subject')),
                ('subject', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hub_academic.subject')),
            ],
        ),
    ]
