# Generated by Django 5.2.5 on 2025-09-04 20:10

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('hub_academic', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='coord',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='courseclass',
            name='course',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='course_class', to='hub_academic.course'),
        ),
        migrations.AddField(
            model_name='ppc',
            name='course',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hub_academic.course'),
        ),
        migrations.AddField(
            model_name='curriculum',
            name='ppc',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='curriculum', to='hub_academic.ppc'),
        ),
        migrations.AddField(
            model_name='curriculum',
            name='pre_requisits',
            field=models.ManyToManyField(to='hub_academic.subject'),
        ),
        migrations.AddField(
            model_name='curriculum',
            name='subject',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ppc', to='hub_academic.subject'),
        ),
    ]
