# Generated by Django 5.2.4 on 2025-07-23 16:04

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hub_academic', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='workload',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='ppc',
            name='subject',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subject', to='hub_academic.subject'),
        ),
        migrations.CreateModel(
            name='CourseClass',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('number', models.CharField(max_length=3, unique=True)),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='course_class', to='hub_academic.course')),
            ],
        ),
        migrations.DeleteModel(
            name='Class',
        ),
    ]
