# Generated by Django 5.2.5 on 2025-09-20 20:44

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hub_academic', '0002_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='category',
            field=models.CharField(choices=[('Técnico Subsequente ao Ensino Médio', 'Tec Sub Em'), ('Técnico Integrado ao Ensino Médio', 'Tec Emi'), ('Educação de Jovens e Adultos (ProEJA)', 'Tec Proeja'), ('Especialização', 'Espec'), ('Superior', 'Sup')], max_length=37, verbose_name='Categoria'),
        ),
        migrations.AlterField(
            model_name='course',
            name='coord',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Coordenador'),
        ),
        migrations.AlterField(
            model_name='course',
            name='name',
            field=models.CharField(max_length=100, unique=True, verbose_name='Nome'),
        ),
        migrations.AlterField(
            model_name='course',
            name='workload',
            field=models.IntegerField(verbose_name='Carga Horária'),
        ),
        migrations.AlterField(
            model_name='courseclass',
            name='course',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='course_class', to='hub_academic.course', verbose_name='Curso'),
        ),
        migrations.AlterField(
            model_name='courseclass',
            name='number',
            field=models.CharField(max_length=3, unique=True, verbose_name='Número'),
        ),
        migrations.AlterField(
            model_name='curriculum',
            name='period',
            field=models.IntegerField(verbose_name='Período'),
        ),
        migrations.AlterField(
            model_name='curriculum',
            name='ppc',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='curriculum', to='hub_academic.ppc', verbose_name='PPC'),
        ),
        migrations.AlterField(
            model_name='curriculum',
            name='pre_requisits',
            field=models.ManyToManyField(to='hub_academic.subject', verbose_name='Pré-requisitos'),
        ),
        migrations.AlterField(
            model_name='curriculum',
            name='subject',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ppc', to='hub_academic.subject', verbose_name='Disciplina'),
        ),
        migrations.AlterField(
            model_name='curriculum',
            name='subject_ext_workload',
            field=models.IntegerField(verbose_name='Carga horária de extensão'),
        ),
        migrations.AlterField(
            model_name='curriculum',
            name='subject_remote_workload',
            field=models.IntegerField(verbose_name='Carga horária remota'),
        ),
        migrations.AlterField(
            model_name='curriculum',
            name='subject_teach_workload',
            field=models.IntegerField(verbose_name='Carga horária de ensino'),
        ),
        migrations.AlterField(
            model_name='curriculum',
            name='weekly_periods',
            field=models.IntegerField(verbose_name='Períodos semanais'),
        ),
        migrations.AlterField(
            model_name='ppc',
            name='course',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hub_academic.course', verbose_name='Curso'),
        ),
        migrations.AlterField(
            model_name='ppc',
            name='created_at',
            field=models.DateField(auto_now_add=True, verbose_name='Data de criação'),
        ),
        migrations.AlterField(
            model_name='ppc',
            name='title',
            field=models.CharField(max_length=100, unique=True, verbose_name='Título'),
        ),
        migrations.AlterField(
            model_name='subject',
            name='code',
            field=models.CharField(max_length=15, unique=True, verbose_name='Código'),
        ),
        migrations.AlterField(
            model_name='subject',
            name='created_at',
            field=models.DateField(auto_now_add=True, verbose_name='Data de criação'),
        ),
        migrations.AlterField(
            model_name='subject',
            name='menu',
            field=models.TextField(verbose_name='Ementa'),
        ),
        migrations.AlterField(
            model_name='subject',
            name='name',
            field=models.CharField(max_length=100, verbose_name='Disciplina'),
        ),
        migrations.AlterField(
            model_name='subject',
            name='objective',
            field=models.TextField(verbose_name='Objetivo geral'),
        ),
    ]
