# Generated by Django 5.2.4 on 2025-07-23 17:57

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hub_academic', '0002_alter_course_workload_alter_ppc_subject_courseclass_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='ppc',
            name='created_at',
            field=models.DateField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
