# Generated by Django 5.2.4 on 2025-07-23 19:50

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hub_academic', '0003_ppc_created_at'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ppc',
            name='pre_requisits',
        ),
        migrations.RemoveField(
            model_name='ppc',
            name='subject',
        ),
        migrations.RemoveField(
            model_name='ppc',
            name='subject_ext_workload',
        ),
        migrations.RemoveField(
            model_name='ppc',
            name='subject_remote_workload',
        ),
        migrations.RemoveField(
            model_name='ppc',
            name='subject_teach_workload',
        ),
        migrations.RemoveField(
            model_name='ppc',
            name='weekly_periods',
        ),
        migrations.CreateModel(
            name='PPCSubjects',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('subject_teach_workload', models.IntegerField()),
                ('subject_ext_workload', models.IntegerField()),
                ('subject_remote_workload', models.IntegerField()),
                ('weekly_periods', models.IntegerField()),
                ('ppc', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hub_academic.ppc')),
                ('pre_requisits', models.ManyToManyField(to='hub_academic.subject')),
                ('subject', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ppc', to='hub_academic.subject')),
            ],
        ),
    ]
