# Generated by Django 5.2.5 on 2026-09-10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hub_academic', '0004_alter_subject_code'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='curriculum',
            constraint=models.UniqueConstraint(
                fields=('ppc', 'subject'),
                name='unique_subject_per_ppc',
            ),
        ),
    ]