# Generated by Django 5.2.4 on 2025-07-26 15:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hub_academic', '0005_ppcsubject_delete_ppcsubjects'),
    ]

    operations = [
        migrations.AddField(
            model_name='subject',
            name='shortname',
            field=models.CharField(default='Sigla', max_length=7),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='course',
            name='category',
            field=models.CharField(choices=[('Técnico Subsequente ao Ensino Médio', 'Tec Sub Em'), ('Técnico Integrado ao Ensino Médio', 'Tec Emi'), ('Educação de Jovens e Adultos (ProEJA)', 'Tec Proeja'), ('Especialização', 'Espec'), ('Superior', 'Sup')], max_length=37),
        ),
    ]
