# Generated by Django 5.2.4 on 2025-07-27 15:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hub_academic', '0006_subject_shortname_alter_course_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subject',
            name='shortname',
            field=models.CharField(max_length=7, unique=True),
        ),
    ]
