# Generated by Django 5.2.4 on 2025-07-29 17:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hub_academic', '0007_alter_subject_shortname'),
    ]

    operations = [
        migrations.AddField(
            model_name='ppcsubject',
            name='period',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
