# Generated by Django 5.2.4 on 2025-07-31 16:53

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hub_academic', '0008_ppcsubject_period'),
    ]

    operations = [
        migrations.CreateModel(
            name='Curriculum',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('subject_teach_workload', models.IntegerField()),
                ('subject_ext_workload', models.IntegerField()),
                ('subject_remote_workload', models.IntegerField()),
                ('period', models.IntegerField()),
                ('weekly_periods', models.IntegerField()),
                ('ppc', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='curriculum', to='hub_academic.ppc')),
                ('pre_requisits', models.ManyToManyField(to='hub_academic.subject')),
                ('subject', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ppc', to='hub_academic.subject')),
            ],
        ),
        migrations.DeleteModel(
            name='PPCSubject',
        ),
    ]
