# Generated by Django 5.2.4 on 2025-08-13 17:59

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hub_academic', '0009_curriculum_delete_ppcsubject'),
    ]

    operations = [
        migrations.RenameField(
            model_name='subject',
            old_name='shortname',
            new_name='code',
        ),
        migrations.AddField(
            model_name='subject',
            name='created_at',
            field=models.DateField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
