# Generated by Django 5.2.4 on 2025-08-13 18:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hub_academic', '0010_rename_shortname_subject_code_subject_created_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subject',
            name='code',
            field=models.CharField(max_length=15, unique=True),
        ),
    ]
