# Generated by Django 5.2.5 on 2025-09-04 21:15

import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='System',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=50, unique=True)),
                ('system_url', models.URLField(max_length=255)),
                ('is_active', models.BooleanField()),
                ('api_key', models.CharField(max_length=255)),
                ('current_state', models.CharField(choices=[('Em desenvolvimento', 'Dev'), ('Implantado', 'Deployed')], max_length=20)),
                ('secret_key', models.CharField(max_length=200)),
                ('dev_team', models.ManyToManyField(to=settings.AUTH_USER_MODEL)),
                ('groups', models.ManyToManyField(to='auth.group')),
            ],
        ),
    ]
