# Generated by Django 5.2.5 on 2025-08-26 23:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hub_systems', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='system',
            name='api_key',
            field=models.CharField(default='aksjdhaskjdhasdhassdaskjdhaskjdh', max_length=255),
            preserve_default=False,
        ),
    ]
