# Generated by Django 5.2.5 on 2025-09-11 16:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hub_systems', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='system',
            name='groups',
        ),
    ]
