# Generated by Django 5.2.5 on 2025-09-20 20:44

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hub_systems', '0002_remove_system_groups'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='system',
            name='api_key',
            field=models.CharField(max_length=255, verbose_name='Chave de API'),
        ),
        migrations.AlterField(
            model_name='system',
            name='current_state',
            field=models.CharField(choices=[('Em desenvolvimento', 'Dev'), ('Implantado', 'Deployed')], max_length=20, verbose_name='Estado atual'),
        ),
        migrations.AlterField(
            model_name='system',
            name='dev_team',
            field=models.ManyToManyField(to=settings.AUTH_USER_MODEL, verbose_name='Equipe DEV'),
        ),
        migrations.AlterField(
            model_name='system',
            name='is_active',
            field=models.BooleanField(verbose_name='Status'),
        ),
        migrations.AlterField(
            model_name='system',
            name='name',
            field=models.CharField(max_length=50, unique=True, verbose_name='Nome'),
        ),
        migrations.AlterField(
            model_name='system',
            name='secret_key',
            field=models.CharField(max_length=200, verbose_name='Chave secreta'),
        ),
        migrations.AlterField(
            model_name='system',
            name='system_url',
            field=models.URLField(max_length=255, verbose_name='URL do sistema'),
        ),
    ]
