# Generated by Django 5.2.3 on 2025-06-30 20:44

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='GroupUUIDMap',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('group', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='uuid_map', to='auth.group')),
            ],
        ),
        migrations.CreateModel(
            name='PermissionUUIDMap',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('permission', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='uuid_map', to='auth.permission')),
            ],
        ),
    ]
