# Generated by Django 5.2.4 on 2025-07-13 20:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_groupuuidmap_permissionuuidmap'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='permissionuuidmap',
            name='permission',
        ),
        migrations.DeleteModel(
            name='GroupUUIDMap',
        ),
        migrations.DeleteModel(
            name='PermissionUUIDMap',
        ),
    ]
