# Generated by Django 5.2.4 on 2025-07-14 19:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_remove_permissionuuidmap_permission_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='access_profile',
            field=models.CharField(choices=[('aluno', 'Aluno'), ('servidor', 'Servidor'), ('convidado', 'Convidado')], default='servidor', max_length=12),
            preserve_default=False,
        ),
    ]
