# Generated by Django 5.2.4 on 2025-07-17 18:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_customuser_access_profile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studentadditionalinfos',
            name='category',
            field=models.CharField(choices=[('Integrado', 'Emi'), ('ProEJA', 'Proeja'), ('Geral', 'Geral')], max_length=15),
        ),
    ]
